config/routes.rb
Rails.application.routes.draw do
  get 'suggest', to: 'search#suggest'
  get 'search',  to: 'search#index'

  resources :artists, only: [:index, :new, :create, :show, :delete]
  resources :albums, only: [:new, :create]
  root to: 'artists#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album
  class Validator < ActiveModel::Validator

    ERROR_MESSAGE = 'An album must be associated with an artist.'.freeze

    def validate(album)
      unless album.title && album.artist && album.artist.persisted?
        album.errors.add(:base, ERROR_MESSAGE)
      end
    end
  end
end

class Album
  include ActiveModel::Model
  include ActiveModel::Validations
  validates_with Validator

  ATTRIBUTES = [:id,
                :artist,
                :label,
                :tracklist,
                :title,
                :released,
                :notes]
  attr_accessor(*ATTRIBUTES)
  validates :title, presence: true

  def initialize(attr={})
    attr.each do |k,v|
      if ATTRIBUTES.include?(k.to_sym)
        send("#{k}=", v)
      end
    end
  end

  def attributes
    ATTRIBUTES.inject({}) do |hash, attr|
      if attr != :artist && value = send(attr)
        hash[attr] = value
      end
      hash
    end
  end
  alias :to_hash :attributes

  def id
    @id || @_id
  end

  def to_param
    id
  end

  def persisted?
    !!id
  end

  def valid?(options={})
    super
    !!(artist && artist.id)
  end
end

app/models/artist.rb
class Artist
  include ActiveModel::Model
  include ActiveModel::Validations

  ATTRIBUTES = [:name,
                :id,
                :_id,
                :profile,
                :date,
                :members,
                :members_combined,
                :urls]
  attr_accessor(*ATTRIBUTES)
  attr_reader :attributes

  validates :name, presence: true

  def initialize(attr={})
    attr.each do |k,v|
      if ATTRIBUTES.include?(k.to_sym)
        send("#{k}=", v)
      end
    end
  end

  def attributes
    ATTRIBUTES.inject({}) do |hash, attr|
      if value = send(attr)
        hash[attr] = value
      end
      hash
    end
  end
  alias :to_hash :attributes

  def id
    @id || @_id
  end

  def to_param
    id
  end

  def persisted?
    !!id
  end

  def members(mems = nil)
    return @members = mems if mems
    @members ||= []
  end
end

app/models/suggester.rb
class Suggester
  attr_reader :response

  def initialize(params={})
    @term = params[:term]
  end

  def execute!(*repositories)
    @responses ||= []
    repositories.each do |repository|
      @responses << begin
        repository.client.search(index: repository.index_name,
                                 body: repository.suggest_body(@term))
      end
    end
  end

  def as_json(options={})
    json = []
    @responses.each do |response|
      results = {}
      next unless response['suggest']
      ['artist_names', 'artist_members', 'album_title', 'album_tracklist'].each do |result_field|

        if suggestion = response['suggest'][result_field]
          results.merge!(suggestion.inject({}) do |matches, suggestion|
            suggestion['options'].each do |option|
              matches[option['text']] = option['_source']['artist_id'] || option['_id']
            end
            matches
          end)
        end
      end

      if !results.empty?
        json << { label: 'Matches',
                  value: results.map do |matching_text, artist_id|
                    { text: matching_text,
                      url:  "artists/#{artist_id}" }
                  end }

      end
    end
    json
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  rescue_from Elasticsearch::Persistence::Repository::DocumentNotFound do
    render file: "public/404.html", status: 404, layout: false
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    artist = $artist_repository.find(album_params[:artist])
    @album.artist = artist if artist

    respond_to do |format|
      if begin; @album.id = $album_repository.save(@album, refresh: true)['_id']; rescue; false; end
        format.html { redirect_to artist, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def album_params
    params.require(:album).permit(:title, :artist)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]

  rescue_from Elasticsearch::Persistence::Repository::DocumentNotFound do
    render file: "public/404.html", status: 404, layout: false
  end

  def index
    @artists = $artist_repository.all sort: 'name.raw'
  end

  def show
    @albums = $album_repository.albums_by_artist(@artist)
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if begin; @artist.id = $artist_repository.save(@artist, refresh: true)['_id']; rescue; false; end
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @artist_repository.delete(@artist.id, refresh: true)
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_artist
      @artist = $artist_repository.find(params[:id])
    end

    def artist_params
      a = params.require(:artist).permit(:name, :profile, :members, :'date(1i)', :'date(2i)', :'date(3i)')
      a[:members] = a[:members].split(/,\s?/) unless a[:members].is_a?(Array) || a[:members].blank?
      return a
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index

    @artists = $artist_repository.search({
      "query": {
          "bool": {
              "must": {
                  "multi_match": { "query": params[:q],
                                   "fields": ['name^10','members^2','profile']
                                 }
              }
          }
      },
      highlight: {
        tags_schema: 'styled',
        fields: {
          name:    { number_of_fragments: 0 },
          members_combined: { number_of_fragments: 0 },
          profile: { fragment_size: 50 }
        }
      }
    })

    @albums = $album_repository.search({
      "query": {
        "bool": {
                 "must": { "multi_match": {
                             "query": params[:q],
                             "fields": ['title^100','tracklist.title^10','notes^1'] } }
          }
      },
      highlight: {
        tags_schema: 'styled',
        fields: {
          title: { number_of_fragments: 0 },
                 'tracklist.title' => { number_of_fragments: 0 },
                 notes: { fragment_size: 50 }
          }
      }
    })
  end

  def suggest
    suggester = Suggester.new(params)
    suggester.execute!($artist_repository, $album_repository)
    render json: suggester
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper

  def highlight(object, field)
    object.try(:hit).try(:highlight).try(field)
  end

  def highlighted(object, field)
    if h = object.try(:hit).try(:highlight).try(field).try(:first)
      h.html_safe
    else
      field.to_s.split('.').reduce(object) { |result,item| result.try(item) }
    end
  end

end

app/views/albums/new.html.erb
<%= simple_form_for @album do |f| %>
  <%= f.collection_select :artist, $artist_repository.all, :id, :name %>
  <%= f.input :title %>

  <%= f.button :submit %>
<% end %>

app/views/albums/show.html.erb
<div class="artist">
  <header>
    <h1>
      <span class="back"><%= link_to "〈".html_safe, artists_path, title: "Back" %></span>
      <%= @artist.name %>
      <%= button_to 'Edit', edit_artist_path(@artist), method: 'get' %>
    </h1>
  </header>

  <p id="notice"><%= notice %></p>

  <section class="artist-info">
    <span><%= ((mems = @artist.members).blank?) ? '' : mems.to_sentence(last_word_connector: ' and ') %></span> |
    <span><%= pluralize @albums.size, 'album' %></span>
    <p class="artist-profile"><%= @artist.profile %></p>
  </section>

  <section class="albums">
    <% @albums.each do |album| %>
      <%= content_tag :div, class: 'clearfix' do %>
        <h3>
          <span class="title"><%= album.title %></span>
          <div class="info">
            <small><%= album.released %></small>
          </div>
        </h3>
      <% end %>

    <% end %>

    <script>$('img').on('error', function(){ $(this).attr('src', '/images/blank_cover.png'); });</script>
    <script>$(document.location.hash).effect('highlight', 1500)</script>
  </section>
</div>

app/views/artists/_form.html.erb
<%= simple_form_for @artist do |f| %>
  <%= f.input :name %>
  <%= f.input :profile, as: :text %>
  <%= f.input :members, hint: 'Separate names by comma', input_html: { value: f.object.members.join(', ') } %>

  <%= f.button :submit %>
<% end %>

app/views/artists/index.html.erb
<header>
  <h1> Artists </h1>
  <%= button_to 'New Artist', new_artist_path, method: 'get', tabindex: 5 %>
  <%= button_to 'New Album', new_album_path, method: 'get', tabindex: 5 %>
</header>

<section id="searchbox">
  <%= form_tag search_path, method: 'get' do %>
    <input type="text" name="q" value="<%= params[:q] %>" id="q" autofocus="autofocus" placeholder="start typing to search..." tabindex="0" />
  <% end %>
</section>

<section class="artists">
  <% @artists.each do |artist| %>
    <%= content_tag :div, class: 'result clearfix' do %>
      <h2>
        <%= link_to artist do %>
          <span class="name"><%= artist.name %></span>
          <small><%= pluralize $album_repository.album_count_by_artist(artist), 'album' %></small>
        <% end %>
      </h2>
    <% end %>
  <% end %>
</section>

<% if @artists.empty? %>
  <section class="no-results">
    <p>The search hasn't returned any results...</p>
  </section>
<% end %>

<script>Search.init();</script>
<script>$('img.band').on('error', function(){ $(this).attr('src', '/images/blank_artist.png'); });</script>

app/views/artists/new.html.erb
<%= simple_form_for @artist do |f| %>
  <%= f.input :name %>
  <%= f.input :profile, as: :text %>
  <%= f.input :members, hint: 'Separate names by comma', input_html: { value: f.object.members.join(', ') } %>

  <%= f.button :submit %>
<% end %>

app/views/artists/show.html.erb
<div class="artist">
  <header>
    <h1>
      <span class="back"><%= link_to "〈".html_safe, artists_path, title: "Back" %></span>
      <%= @artist.name %>
    </h1>
  </header>

  <p id="notice"><%= notice %></p>

  <section class="artist-info">
    <span><%= ((mems = @artist.members).blank?) ? '' : mems.to_sentence(last_word_connector: ' and ') %></span> |
    <span><%= pluralize @albums.size, 'album' %></span>
    <p class="artist-profile"><%= @artist.profile %></p>
  </section>

  <section class="albums">
    <% @albums.each do |album| %>
      <%= content_tag :div, class: 'clearfix' do %>
        <h3>
          <span class="title"><%= album.title %></span>
          <div class="info">
            <small><%= album.released %></small>
          </div>
        </h3>
      <% end %>

    <% end %>

    <script>$('img').on('error', function(){ $(this).attr('src', '/images/blank_cover.png'); });</script>
    <script>$(document.location.hash).effect('highlight', 1500)</script>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.action_name %>">

  <header>
    <h1>
      Sample Music app
    </h1>
  </header>
  <p></p>
    <%= yield %>
  </body>
</html>

app/views/search/index.html.erb
<header>
  <h1>
    <span class="back"><%= link_to "〈".html_safe, :back, title: "Back" %></span>
    Artists &amp; Albums
  </h1>
</header>

<section id="searchbox">
<%= form_tag search_path, method: 'get' do %>
  <input type="text" name="q" value="<%= params[:q] %>" id="q" autofocus="autofocus" placeholder="start typing to search..." tabindex="0" />
<% end %>
</section>

<section class="artists">
  <% @artists.each do |artist| %>
    <%= content_tag :div, class: 'artist search result clearfix' do %>
      <h2>
        <%= link_to artist do %>
          <span class="name"><%= highlighted(artist, :name) %></span>
          <small><%= pluralize $album_repository.album_count_by_artist(artist), 'album' %></small>
        <% end %>
      </h2>
      <% if highlight = highlight(artist, :members_combined) %>
      <p class="highlight small">
        <span class="label">Members</span>
        <%= highlight.first.html_safe %>
      </p>
      <% end %>
      <% if highlight = highlight(artist, :profile) %>
      <p class="highlight small">
        <span class="label">Profile</span>
        <%= highlight.join('&hellip;').html_safe %>
      </p>
      <% end %>
    <% end %>
  <% end %>
</section>

<section class="albums">
  <% @albums.each do |album| %>
    <%= content_tag :div, class: 'album search result clearfix' do %>
      <h2>
        <%= link_to artist_path album.artist_id do %>
          <span class="name"><%= album.artist_name %></span>
        <% end %> |
        <span class="name"><%= highlighted(album, :title) %></span>
      </h2>

      <% if highlight = highlight(album, 'tracklist.title') %>
        <p class="highlight small">
          <span class="label">Tracks</span>
          <%= highlight.join('&hellip;').html_safe %>
        </p>
      <% end %>

      <% if highlight = highlight(album, :notes) %>
        <p class="highlight small">
          <span class="label">Notes</span>
          <%= highlight.map { |d| d.gsub(/^\.\s?/, '') }.join('&hellip;').html_safe %>
        </p>
      <% end %>
    <% end %>
  <% end %>
</section>

<% if @artists.empty? && @albums.empty? %>
<section class="no-results">
  <p>The search hasn't returned any results...</p>
</section>
<% end %>

<script>Search.init();</script>